# Generated by Django 2.2 on 2021-02-26 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('language', models.CharField(choices=[('BANGLA', 'Bangla'), ('ENGLISH', 'English'), ('ARABIC', 'Arabic'), ('URDU', 'Urdu')], default='BANGLA', max_length=32)),
                ('category', models.CharField(choices=[('Spirituality', 'Spirituality'), ('Tafseer', 'Tafseer'), ('Hadith', 'Hadith'), ('Aqeedah', 'Aqeedah')], default='Spirituality', max_length=32)),
                ('publication', models.CharField(choices=[('None', 'None'), ('A', 'A'), ('B', 'B'), ('C', 'C')], default='None', max_length=32)),
                ('details', models.TextField()),
                ('Author', models.CharField(max_length=32)),
                ('image', models.ImageField(upload_to='%Y/%m/%d')),
            ],
        ),
    ]
